input GuestInput {
  name: String!
}

type Guest {
  id: ID!,
  name: String!,
  dietaryRestrictions: [String]!
}

type Query {
  guests: [Guest]!
  guest(id: ID!): Guest!
}

type Mutation {
  createGuest(input: GuestInput!): Guest
  addDietaryRestriction(guestId: ID!, dietaryRestriction: String!): Guest!
}
