export const DINNERS_CREATE_NEXT_DINNER_REQUEST = 'DINNERS_CREATE_NEXT_DINNER_REQUEST';
export const DINNERS_CREATE_NEXT_DINNER_SUCCESS = 'DINNERS_CREATE_NEXT_DINNER_SUCCESS';
export const DINNERS_CREATE_NEXT_DINNER_FAILURE = 'DINNERS_CREATE_NEXT_DINNER_FAILURE';
