export const DINNERS_FETCH_DINNERS_REQUEST = 'DINNERS_FETCH_DINNERS_REQUEST';
export const DINNERS_FETCH_DINNERS_SUCCESS = 'DINNERS_FETCH_DINNERS_SUCCESS';
export const DINNERS_FETCH_DINNERS_FAILURE = 'DINNERS_FETCH_DINNERS_FAILURE';

export const DINNERS_CREATE_NEXT_DINNER_REQUEST = 'DINNERS_CREATE_NEXT_DINNER_REQUEST';
export const DINNERS_CREATE_NEXT_DINNER_SUCCESS = 'DINNERS_CREATE_NEXT_DINNER_SUCCESS';
export const DINNERS_CREATE_NEXT_DINNER_FAILURE = 'DINNERS_CREATE_NEXT_DINNER_FAILURE';

export const DINNERS_INVITE_GUEST_REQUEST = 'DINNERS_INVITE_GUEST_REQUEST';
export const DINNERS_INVITE_GUEST_SUCCESS = 'DINNERS_INVITE_GUEST_SUCCESS';
export const DINNERS_INVITE_GUEST_FAILURE = 'DINNERS_INVITE_GUEST_FAILURE';
