export const GUESTS_CREATE_GUEST_REQUEST = 'GUESTS_CREATE_GUEST_REQUEST';
export const GUESTS_CREATE_GUEST_SUCCESS = 'GUESTS_CREATE_GUEST_SUCCESS';
export const GUESTS_CREATE_GUEST_FAILURE = 'GUESTS_CREATE_GUEST_FAILURE';

export const GUESTS_FETCH_GUESTS_REQUEST = 'GUESTS_FETCH_GUESTS_REQUEST';
export const GUESTS_FETCH_GUESTS_SUCCESS = 'GUESTS_FETCH_GUESTS_SUCCESS';
export const GUESTS_FETCH_GUESTS_FAILURE = 'GUESTS_FETCH_GUESTS_FAILURE';

export const GUESTS_SET_TRANSIENT_GUEST_NAME = 'GUESTS_SET_TRANSIENT_GUEST_NAME';
